name: Esegue Playbook Ansible e invia notifica in caso di successo

on:
  push:
    branches: [ main ]

jobs:
  job_1_esegui_playbook:
    #runs-on: ubuntu-latest
    runs-on: vps-ubuntu-ovh
    container:
      image: almalinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Imposta container AlmaLinux-9
      #   uses: docker/setup-qemu@v2
      #   with:
      #     image: quay.io/almalinux/almalinux:9

      - name: Installa Ansible se non presente
        run: |
          if ! which ansible-playbook > /dev/null 2>&1 ; then 
            python -m pip install --upgrade pip
            pip install ansible
          fi

      - name: Esegue playbook Ansible
        id: esegui-playbook
        run: |
          ansible-playbook playbook_1.yaml


  jobs_2_se_successo:
    runs-on: vps-ubuntu-ovh
    if: success() 
    needs: esegui-playbook
    steps:

      - name: esegue playbook 2
        id: esegui-playbook
        run: |
          ansible-playbook playbook_2.yaml

      - name: Invia notifica via email in caso di successo
        uses: actions/notify@v2
        with:
          email: utente@example.com
          subject: Playbook Ansible eseguito con successo!
          body: Il playbook Ansible è stato eseguito con successo sul branch ${{ github.event.ref.name }}.
