name: Install Ansible

on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-22.04

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.10.12

#     - name: print hostname
#       run: hostname

#     - name: Install Ansible
#       run: |
#         python -m pip install --upgrade pip
#         pip install ansible

#     - name: Run playbook_1
#       run: |
#         ansible-playbook playbook_1.yaml



#######################
## Container ansible ##
#######################
## All’interno della macchina virtuale, puoi scegliere di eseguire i tuoi jobs all’interno di un container Docker,
## utilizzando il campo container nel file di workflow. 
## In questo caso, tutti i passaggi del job che non specificano già un container verranno eseguiti all’interno del container Docker.
##
## NOTE: ansible non è installato nel container.
## Va installato:
## apt update && apt install ansible
## 
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ansible/ansible:ubuntu1404

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # - name: Run Ansible playbook
      #   run: ansible-playbook playbook_1.yaml

      - name: execute hostname
        run: hostname

      - name: install ansible 
        run: |
          apt -y update
          apt -y install ansible

      - name: Run playbook_1
        run: |
          ansible-playbook playbook_1.yaml
